### ISSUE TITLE
Let passage titles appear in Outline

### ISSUE THREAD

**Issue by DustinWoods** [cyrusfirheir/twee3-language-tools#1]
This is a duplication of an issue from the extension I've been managing over here: https://github.com/DustinWoods/vscode-twee2-syntax/issues/8

Considering the amount of effort already put into this extension, it may be simpler to implement this feature here instead!

For reference, the outline is located beneath the file explorer and look like this currently with twee extension enabled:
![Screenshot from 2020-08-17 14-00-09](https://user-images.githubusercontent.com/5541776/90444033-0ca1d180-e092-11ea-9faf-1454bd9f01bb.png)

This functionality has already been implemented with the passage list feature. Would there be any benefit to having this in the outline instead, or in addition to?

As far as I understand the outline pane, symbols would need to be described in the language server for passage titles, and these would be recognized for the outline hierarchy.

**Comment by cyrusfirheir** [comment]
My original idea with the extra view container was that it'd have more tabs. Only have passages for now, and when new ideas pop up, I'll add them in.

But adding them to the outline section doesn't sound like a bad idea. I'll look into it.

**Comment by cyrusfirheir** [comment]
Okay, if I'm understanding this correctly, the Outline view lists all the symbols in the active document. Could be useful... But I'm more inclined towards having a simple filter/sort button in the existing passage list which pushes the passages in the current file to the top.

And if this is about having to navigate to another view container, you can always drag the passage list out and dock it under the file explorer. Pushing stuff to the Outline view seems like needless extra work.

Unless there are some other benefits I'm not seeing, of course.

**Comment by DustinWoods** [comment]
I think you're probably right! The original user who brought this up was @wkc1986. I pointed them here to your extension, which may solve their problem.

But yeah it might be needless work if nobody needs it, and it sounds like the passage list you built does a lot more than list symbols.

**Comment by wkc1986** [comment]
Thanks for this great extension which I didn't know at first but Dustin directed me to. I think the current passage list is great, especially as it scans all Twee files in the working directory--it would be great if there were a way to filter for passages from the current file, or with a tag.

**Comment by cyrusfirheir** [comment]
Yes, sorting, filtering, grouping, all of that good stuff is planned.

**Comment by cyrusfirheir** [comment]
@wkc1986 commented on Aug 26
> Thanks for this great extension which I didn't know at first but Dustin directed me to. I think the current passage list is great, especially as it scans all Twee files in the working directory--it would be great if there were a way to filter for passages from the current file, or with a tag.

v0.5.0 adds grouping by file and tags. Hope this helps!
