### ISSUE TITLE
Preview passages and simple edit

### ISSUE THREAD

**Issue by SjoerdHekking** [cyrusfirheir/twee3-language-tools#102]
Dear,

I think the step from Twine Editor to VSC + T3LT is a little "big" especially since Twine Editor workflow focuses on opening passages by double click and editing them within the "map". I think the user could greatly benefit from a syntax highlighted preview window, which allows editing to quickly change brackets, move stuff around, or add simple dialogue/story without having to switch from VSC to the map constantly. 

Moreover, it would be beyond amazing if we can get the multi-window function from Twine 1 back, which allows users to open two smaller preview windows, quickly swap a few statements, for example, if-else functions, and be on their merry way, without having to move from VSC to the map and loop.

This could greatly speed up workflow and encourage Twine editor users to move to an advanced tool to aid them in making neat stories without the limits of no syntax highlights from the Twine editor, resulting in a maybe higher net gain of total users.

**Comment by cyrusfirheir** [comment]
Published v0.17.0 ([7a9b2d0](https://github.com/cyrusfirheir/twee3-language-tools/commit/7a9b2d00c63dfdebf73a1eb26422cb630ece71e2)).

Now the Story Map opens in a webview inside VSCode. No need to juggle an extra browser window.
