### ISSUE TITLE
VSCode webview reloads on focus

### ISSUE THREAD

**Issue by Joeyrsp** [cyrusfirheir/twee3-language-tools#103]
When I double click a passage to open it in an editor pane and it opens in the same pane as the map, switching back to the map loads it again.

I haven't looked into the codebase at all yet so I can't offer any insight but I wonder what sort of persistence options there are.

**Comment by richrobber2** [comment]
whenever the panel is not displayed going back to it the map just does not load back in I currently have to keep it open and on one screen its not really doable
