### ISSUE TITLE
Extra ' mark added automatically when bolding text at the end of the bolded text

### ISSUE THREAD

**Issue by Philip-Sutton** [cyrusfirheir/twee3-language-tools#109]
When using T3LT in VSCode, if I go to bold the word 'text' this is what happens:

When I put '' in front of text and then '' at the end, an extra ' is automatically inserted, so I get:

''text'''

**Comment by Tranberry** [comment]
https://user-images.githubusercontent.com/16529/161400634-ffdb3ea4-8b59-46f9-bacd-500aace876ce.mp4

Is this what you are experiencing?

**Comment by Philip-Sutton** [comment]
No - it looks like this
![T3LT issue](https://user-images.githubusercontent.com/1549449/161404284-939413a1-756c-48eb-8883-af816a748295.gif)
:

**Comment by MinusGix** [comment]
Try changing the vscode setting named "Auto Surround" to either 'brackets' or 'never'.

**Comment by Philip-Sutton** [comment]
@MinusGix  -  thanks

**Comment by Tranberry** [comment]
(it is the same thing) 👍
