### ISSUE TITLE
Using autocomplete to type the <<return>> macro

### ISSUE THREAD

**Issue by Philip-Sutton** [cyrusfirheir/twee3-language-tools#110]
If you type "r" in vscode with T3LT running, this triggers the opening of a list of autocomplete options.  If you select :return then vscode autocompletes by inserting `<<return >>`

This autocomplete text has a space after the word 'return' and before the first closing angle bracket - which should not be there, though the macro still works when rendered into the output .html file.

**Comment by cyrusfirheir** [comment]
The return macro optionally allows custom text/images for the link, hence the blank space in the snippet.

https://www.motoslave.net/sugarcube/2/docs/#macros-macro-return
