### ISSUE TITLE
New (July) update causes CPU to run continuously

### ISSUE THREAD

**Issue by CapAbraham** [cyrusfirheir/twee3-language-tools#136]
Normally, VS Code with Twee3 installed runs at 0 to 5% CPU usage, but the new update appears to cause this to spike constantly to 25%.

**Comment by SjoerdHekking** [comment]
I did some testing with older versions of T3LT, but I can't seem to reproduce what is happening to you. T3LT runs the same expected results for several versions for me: 

1. 50% - Starting VSC (2 seconds)
2. 15% - Counting all passages (20 seconds, for 2500 passages)
3. 25% - Finishing extension startup (3 seconds)
4. 5% - Stable while typing/editing random things. (roughly a minute tested)

Just so you know, our CPUs aren't the same, and even if they were, internally they aren't 1:1. That said, I highly doubt your problem originates from T3LT anyway. Is your computer updating in the background e.g. Windows, or are you running anything else in the background?

**Comment by CapAbraham** [comment]
Thanks for your quick reply which made me go back and reload each of my extensions and experiment further.  It turns out that this is happening when I run open one particular folder with Twee3.  So, Twee3 is misbehaving, but the problem seems to be triggered by something in this folder.

But otherwise, yes, Twee3 does appear to be working fine.  Now, I just have to discover what the offending object is in this folder that's triggering the Extension in this manner.

Thanks!
