### ISSUE TITLE
Large Files and Performance

### ISSUE THREAD

**Issue by MinusGix** [cyrusfirheir/twee3-language-tools#14]
Currently, with large files (such as this 30,000 line one), the extension can slow down quite a bit. Sometimes even becoming unresponsive (it became unresponsive on that file for 6 seconds, but whether that was because it finally finished or vscode stopped it, dunno).  
This was *without* argument parsing enabled (or parameter validation), and would only be worse with those enabled.
  
**Improving performance on large files would be useful:**
  - Cache `collect`. If we can tell whether a file has changed since we last saw it, we don't need to redo this (but this does mean that we have to keep the data around). This would be _very_ good for performance I believe, since it is called very often. While even *large* twine files are usually only on the order of megabytes rather than gigabytes, Javascript will use up a good amount of memory for data and so care *might* need to be taken. I think there is an inbuilt vscode feature for having a unique-id/incrementing-id to keep track of file changes which could be used.  
    - But of course, just a cache on the file wouldn't be the greatest for large files if you're editing them at all. Theoretically could try tracking where edits occur (in passages within the file to make it saner and simpler to implement?) then somehow only update the `collect` results for the edited passage.
  - Cache argument parsing (and parameter validation once the PR is done). I already have some ideas on this which are somewhat detailed in the PR for parameter validation.   
  
**Gracefully Handling it**: Important as well, since there will be inputs which we can't manage, is that of gracefully handling it.  
The largest files we'll get are probably from those who want to switch their Twine project to use Twee, decompile it to a single file, then check it out. If they see lag and weirdness, they're less likely to stay with it.  
I'm uncertain of the best way to do this. Time checking so if an operation takes longer than a certain amount of time it alerts the user that the file is very large? Automatic notifying the user when they open a large file that it works better in smaller files? Does vscode provide any utilities to automatically do this?  
  
**Horizontal Note**: Adding support for breaking apart the passages in a Twine archive into separate files to Tweego would help with this automagically, since we'd be less likely to get really large files. Though, it is written in Golang, and while I'd be able to manage learning it, I haven't used it barely any.

**Comment by cyrusfirheir** [comment]
> Adding support for breaking apart the passages in a Twine archive into separate files to Tweego would ...
While TME does [wanna do it](https://github.com/tmedwards/tweego/issues/3) someday, right now whenever I find anyone wanting to switch to a compiler, I lend them a node script to split the monolith into separate files.
