### ISSUE TITLE
Large Twee 3 Projects have a hard time with vscode.

### ISSUE THREAD

**Issue by thakyZ** [cyrusfirheir/twee3-language-tools#157]
I am getting a warning, along with a lot of lag in my VSCode instance
```
2024-04-23 19:51:13.269 [warning] [mainThreadStorage] large extension state detected (extensionId: cyrusfirheir.twee3-language-tools, global: false): 6522.494140625kb. Consider to use 'storageUri' or 'globalStorageUri' to store this data on disk instead.
```
The passage count is `11463` and it isn't very useful with this amount of lag. Might I propose following what it says in the warning for large states?

**Comment by Tranberry** [comment]
What kind of passages are the bulk of these `11463` passages? 
Without any context I would assume step one would be move logic from twee into pure js files. I'm also assuming that you use one of the more JS friendly `storyformats`.

**Comment by thakyZ** [comment]
I have been informed your team already knows about the issue. I will just close this.
