### ISSUE TITLE
在py檔中按下enter鍵不能換行

### ISSUE THREAD

**Issue by Paul-16098** [cyrusfirheir/twee3-language-tools#159]
Type: <b>Bug</b>

在py檔中按下enter鍵不能換行

Extension version: 0.25.3
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (1.29GB free)|
|Process Argv|C:\\Users\\p\\tools\\n\\DoL-ModLoader\\run.py --crash-reporter-id a4280153-3bce-4711-90fd-fb32dd197407|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31049070
a69g1124:31046351
pythonprt:31047983
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by SjoerdHekking** [comment]
> en: Pressing the enter key in the py file cannot wrap the line

I doubt this has anything to do with T3LT.

**Comment by Tranberry** [comment]
Are you suggesting that T3LT affects `.py`-files?

**Comment by cyrusfirheir** [comment]
Closing because inactivity.
