### ISSUE TITLE
Collapsible passages

### ISSUE THREAD

**Issue by MxAshUp** [cyrusfirheir/twee3-language-tools#2]
This is a clone of the issue over here: https://github.com/DustinWoods/vscode-twee2-syntax/issues/7

In summary, it would be nice to have passages detected as folding regions so they can be collapsed. This cannot be solved with the folding regions option in a grammar file, but instead needs to be implemented in the language server.

**Comment by cyrusfirheir** [comment]
I already had a `Folding Range Provider` set up, but then found out that custom providers kill indentation based folding.

A regex based folding in language configurations would be ideal, but as both the opening and closing tags are identical, and because it goes line by line, I haven't been able to settle on anything so far.

**Comment by DustinWoods** [comment]
Yeah I tried the regex-based config and ran into the same problem. I never considered this would have issues with indent-based folding. Do you still have the code for this?

**Comment by cyrusfirheir** [comment]
```ts
vscode.languages.registerFoldingRangeProvider({ pattern: "**/*.tw*" }, {
	provideFoldingRanges(document: vscode.TextDocument, context: vscode.FoldingContext) {
		const lines = document.getText().split(/\r?\n/);
		let r: vscode.FoldingRange[] = [];
		let open = 0;
		lines.forEach((el, i) => {
			const last = i === lines.length - 1;
			if (/^::.*/.test(el) || last) {
				if (open < i) r.push(new vscode.FoldingRange(open, i - (last ? 0 : 1), vscode.FoldingRangeKind.Region));
				open = i;
			}
		});
		return r;
	}
});
```

Providers for `CompletionItem` and `FoldingRange` (these I've tested, so far) overwrite normal plaintext behavior. There are issues open in the VSCode repo for this, but I doubt it's going to change anytime soon.

**Comment by mielikki** [comment]
This doc https://code.visualstudio.com/docs/editor/codebasics#_folding seems to indicate that you can turn indentation folding back on if you don't want the syntax aware folding. Does that help? I'm fairly new to twee so I'm not sure when indentation folding would be useful in a twee file?

> Since the 1.22 release, folding regions can also be computed based on syntax tokens of the editor's configured language.
> The following languages already provide syntax aware folding: Markdown, HTML, CSS, LESS, SCSS, and JSON.
>
> If you prefer to switch back to indentation-based folding for one (or all) of the languages above, use:
> ```
>   "[html]": {
>     "editor.foldingStrategy": "indentation"
>   },
> ```
> Regions can also be defined by markers defined by each language. The following languages currently have markers defined:

**Comment by cyrusfirheir** [comment]
@mielikki Unfortunately, no, that doesn't help. Turning it off doesn't help. Having it there allows for some sort of folding for those who do indent...

The problems with folding is described in the previous comments, and they're sadly still the same problems.
