### ISSUE TITLE
Bug regarding "Argument is not text"

### ISSUE THREAD

**Issue by Gampsi** [cyrusfirheir/twee3-language-tools#25]
Hello, there is some bug regarding "Argument is not text". I have a listbox with an option and that option value is "undefined"(without the quotes) but it says that the argument is not a text, this doesn't happen if you put null instead of undefined.

Code example:
```
<<listbox "$selectedrecipe" autoselect>>
     <<option "Select a recipe" undefined>>
     <<optionsfrom $learnedrecipes>>
<</listbox>>
```

**Comment by cyrusfirheir** [comment]
Patched in v0.9.4. Was an issue with argument definitions for the `<<options>>` child macro. Was only looking for text. Now should work with all values.
