### ISSUE TITLE
always generate .vscode config

### ISSUE THREAD

**Issue by caberg** [cyrusfirheir/twee3-language-tools#31]
can we prevent this extension always generate settings.json file even if we doesnt open the twee files ?

**Comment by cyrusfirheir** [comment]
The extension is set to set the language as soon as a twee file is found in the workspace. Preventing that behavior defeats the purpose of having the extension in the first place... Maybe I am not seeing the issue here, but could you explain the problem with it generating a `settings.json` file?

**Comment by caberg** [comment]
here's what i mean
![Code_p5i2NFkhd6](https://user-images.githubusercontent.com/2444037/110236162-e0cf3600-7f66-11eb-91f6-949fb15e872d.jpg)

the extension generate a new setting in my workplace even in my react native project LOL

**Comment by cyrusfirheir** [comment]
It had to have found a `.tw` or `.twee` file in the workspace. The extension doesn't even activate otherwise.

**Comment by GwenTastic** [comment]
i think i know what's happening, it doesn't need to be part of the workspace, it just needs to be opened by the same VSC window. 
![t333333lt](https://user-images.githubusercontent.com/47124765/110242257-7d88d800-7f55-11eb-9381-ca7109278014.gif)

**Comment by cyrusfirheir** [comment]
Patched in `v0.11.5`.
