### ISSUE TITLE
Weird error when making a textbox with sugarcube 2 in a .twee file

### ISSUE THREAD

**Issue by Shain-Allen** [cyrusfirheir/twee3-language-tools#33]
not quite sure what this is but figured I should post it here if not intentional.
so I am trying to port my game over to use Tweego and this extension is helping out a lot but after moving something over that had a macro to make a textbox VS code threw this error 
the text box code ---> Your Name: <<textbox "$name" "" [[GuruIntroduction]]>>
the error it throws ---> Expected literal ('autofocus'), but found:  sc2-ex(109)

it is of note that this does in fact work just fine in the twine editor

**Comment by cyrusfirheir** [comment]
Patched in v0.11.9! Should be working fine now.
