### ISSUE TITLE
Extension forces space after `::` in passage title

### ISSUE THREAD

**Issue by hogart** [cyrusfirheir/twee3-language-tools#4]
While this maybe a better code style, it's just a stylistic choice, and it would be great to have the ability to customize this behavior in extenson options. Especially since the extension doesn't fix this automatically and the users are forced to manual find/replace.

**Comment by cyrusfirheir** [comment]
Added setting `twee3LanguageTools.twee-3.warning.spaceAfterStartToken` to disable the warning. Hope that helps! Automatic fixing is on the list of todos, will get to it soon.

**Comment by hogart** [comment]
Wow, that's fast! Thanks!

**Comment by BawdyInkSlinger** [comment]
@cyrusfirheir Should this issue be resolved?
