### ISSUE TITLE
Custom style formatting is not recognized

### ISSUE THREAD

**Issue by ezsh** [cyrusfirheir/twee3-language-tools#41]
From #40 I assume it has to work, but I see no highlighting for `@@` blocks at all. 

VSCode 1.54.3, extension version 0.13.

**Comment by cyrusfirheir** [comment]
There isn't any highlighting for the custom style markup. That issue mentions that it's a joke...

Everything regarding the `@@;@@` syntax will be handled in future releases. Closing.

**Comment by ezsh** [comment]
Thanks for the prompt reply!
