### ISSUE TITLE
Thoughts on exposing twee passages as functions? 

### ISSUE THREAD

**Issue by idvorkin** [cyrusfirheir/twee3-language-tools#48]
Love having a  VS code plugin!

Would it make sense to model twee passages as functions (not sure the right word for vs.code extension eco system - function or symbol or?? ). 

If passages were functions you could use the outline view, find references, find unused functions, find functions that don't point to anything, etc.

Thoughts on this approach?

**Comment by cyrusfirheir** [comment]
As discussed in #1, I am probably not going to touch the Outline view anytime soon. It is very limited, and providing symbols to it is sorta a pain.

However, there are going to be changes to how stuff is parsed as mentioned in #38. The Outline view could be worth revisiting at that time. The idea has merit, but in the future.

Closing for now.

**Comment by idvorkin** [comment]
I'm guessing the biggest value isn't the outline view, but instead things like: 

goto function
code completion
find reference
find unused functions

Is it symbols in general that's a pain, or just symbols to outline view?  When do you think  #38 is getting tackled ?  I've never worked on a vs. code extension before, but could be fun :)

**Comment by cyrusfirheir** [comment]
You will have to elaborate a bit more on what you mean by those. Goto *macro?* Which is storyformat specific.

Right now, I am not working on the extension till the end of my semester (halfway next month,) so #38 will get handled then.

You're welcome to work on it if you wish to. You can find all the documentation and links to examples you might in [here](https://code.visualstudio.com/api).
