### ISSUE TITLE
Quote marks are being treated as strings

### ISSUE THREAD

**Issue by johnflux** [cyrusfirheir/twee3-language-tools#51]
Single quote marks are being highlighted as strings, in Harlowe 3.

Example:

It's not fair.  I wasn't doing anything.

Will highight in blue everything between the apostraphys: s not fair.  I wasn

**Comment by cyrusfirheir** [comment]
Can you post a screenshot? That shouldn't be happening in plain text. Only inside some syntactical markup.

**Comment by johnflux** [comment]
Ah, I didn't notice the problem is happening everywhere.

It happens, for example, when there's brackets:

:: Foo
('bar')

This shows "bar" in blue.

https://imgur.com/a/RSAF3BR

**Comment by johnflux** [comment]
Also see this.  It thinks the closing bracket is inside a string

:: Foo

Hello (He'd thought).  Isn't it a good day.

**Comment by cyrusfirheir** [comment]
Patched in v0.13.12!

**Comment by johnflux** [comment]
Thanks!
