### ISSUE TITLE
rename "Pack passages..." command with Twee3 prefix

### ISSUE THREAD

**Issue by mielikki** [cyrusfirheir/twee3-language-tools#54]
Thanks for the great tool!

Could we rename the "Pack passages to clusters (Experimental)" command to "Twee3 Language Tools: Pack passages to clusters (Experimental)"?

That way it would be discoverable when we type "twee3" in the command palette seach.

**Comment by cyrusfirheir** [comment]
Edited. Update to v0.13.17.
