### ISSUE TITLE
[SugarCube 2] Incorrect highlighting for linkMarkupList

### ISSUE THREAD

**Issue by mattrossman** [cyrusfirheir/twee3-language-tools#7]
When [passing a `linkMarkupList` into the `<<actions>>` macro](https://www.motoslave.net/sugarcube/2/docs/#macros-macro-actions), highlighting gets messed up for the first argument. This is especially problematic when the first argument contains an apostrophe:

![image](https://user-images.githubusercontent.com/22670878/97940481-ac95ff80-1d51-11eb-976a-243556260a6e.png)

**Comment by mattrossman** [comment]
My bad! My file kept getting formatted with the generic `twee3` style even after I selected `twee3-sc2` for the language mode. Once I specified the SugarCube format in `::StoryData`, it properly switched to `twee3-sc2` and it looks like the actions are formatted properly.

**Comment by cyrusfirheir** [comment]
Yeah, the moment you see the double angle brackets not being highlighted the same way, know that something is wrong.
