### ISSUE TITLE
[SugarCube 2] Apostrophes trigger string highlighting in <<actions>>

### ISSUE THREAD

**Issue by mattrossman** [cyrusfirheir/twee3-language-tools#8]
Sorry for the false alarm yesterday, but this time I have an actual issue 😛 

When two apostrophes appear within `<<actions>>` links, the text within is highlighted as a string even though SugarCube doesn't treat them that way.

This occurs both when the apostrophes are in the same link:
![image](https://user-images.githubusercontent.com/22670878/98067039-a9207800-1e26-11eb-8dd7-df8286215dc5.png)

Or in separate links:
![image](https://user-images.githubusercontent.com/22670878/98066864-46c77780-1e26-11eb-86f8-3f9d296b4211.png)

**Comment by cyrusfirheir** [comment]
Updated to v0.6.3. Should fix it.
